version: '3'

services: 
  atcoder:
    build: './'
    volumes: 
      - './../:/home/:delegated'
      - './../Makefile:/home/Makefile:delegated'
      - './../contest_data.txt:/home/contest_data.txt:delegated'
      - './../lib:/home/lib:delegated'
      - './../scripts:/home/scripts:delegated'
      - './../templates:/home/templates:delegated'
      - '/home/tasks'
      - '/home/samples'
      - '/home/tmp'
      - '/home/ignore_dir'